### PR TITLE
Upgrade to Yarn 2 (Berry)

### PR DESCRIPTION
**Pull request by chase-patterson**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
@chase-patterson - We tested an open source yarn berry project being consumed by a legacy Yarn1 project - https://github.com/sourcetoad/tamagui-react-native.

No issues detected, so this might be mergable.

**Comment by chase-patterson** [comment]
> @chase-patterson - We tested an open source yarn berry project being consumed by a legacy Yarn1 project - https://github.com/sourcetoad/tamagui-react-native.
> 
> No issues detected, so this might be mergable.

Do you think this would be a 2.0 release? If so, it's probably "safe" to merge into master, with that in mind. But we might want a ticket to do some testing/QA so we don't forget (as well as creating the versions in Jira)

**Comment by iBotPeaches** [comment]
> Do you think this would be a 2.0 release? If so, it's probably "safe" to merge into master, with that in mind. But we might want a ticket to do some testing/QA so we don't forget (as well as creating the versions in Jira)

Its probably safe, but probably changing package manager major versions is grounds for a new major version.

**Comment by iBotPeaches** [comment]
> > @chase-patterson - We tested an open source yarn berry project being consumed by a legacy Yarn1 project - https://github.com/sourcetoad/tamagui-react-native.
> > No issues detected, so this might be mergable.
> 
> Do you think this would be a 2.0 release? If so, it's probably "safe" to merge into master, with that in mind. But we might want a ticket to do some testing/QA so we don't forget (as well as creating the versions in Jira)

Created under RETRY-2 internally.

**Comment by iBotPeaches** [comment]
Closing out - RETRY-2 was closed w/ note to move to NPM.

**Pull request closed without merging**
